INSERT INTO team (name) VALUES
    ('France'),
    ('Spain'),
    ('Argentina'),
    ('England'),
    ('Portugal'),
    ('Brazil'),
    ('Netherlands'),
    ('Morocco'),
    ('Belgium'),
    ('Germany'),
    ('Croatia'),
    ('Colombia'),
    ('Senegal'),
    ('Mexico'),
    ('United States'),
    ('Uruguay'),
    ('Japan'),
    ('Switzerland'),
    ('Iran'),
    ('Austria'),
    ('Ecuador'),
    ('Australia'),
    ('South Korea'),
    ('Egypt'),
    ('Canada'),
    ('Ivory Coast'),
    ('Qatar'),
    ('Algeria'),
    ('Sweden'),
    ('Tunisia'),
    ('Czechia'),
    ('Turkiye'),
    ('Norway'),
    ('Scotland'),
    ('DR Congo'),
    ('Bosnia and Herzegovina'),
    ('Panama'),
    ('Saudi Arabia'),
    ('South Africa'),
    ('Iraq'),
    ('Paraguay'),
    ('New Zealand'),
    ('Cape Verde'),
    ('Haiti'),
    ('Jordan'),
    ('Uzbekistan'),
    ('Ghana'),
    ('Curacao')
ON CONFLICT (name) DO NOTHING;
