export const gamblers = {
  reports: [
    {
      userId: 4,
      tournamentId: null,
      name: 'Anh Nguyen',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 135000,
      contribution: 0,
      total: 135000,
    },
    {
      userId: 5,
      tournamentId: null,
      name: 'Snow',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 165000,
      contribution: 0,
      total: 165000,
    },
    {
      userId: 6,
      tournamentId: null,
      name: 'PT',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 125000,
      contribution: 0,
      total: 125000,
    },
    {
      userId: 7,
      tournamentId: null,
      name: 'Cháu chú Gà',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 125000,
      contribution: 0,
      total: 125000,
    },
    {
      userId: 8,
      tournamentId: null,
      name: 'Không Sợ Chó',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 165000,
      contribution: 0,
      total: 165000,
    },
    {
      userId: 9,
      tournamentId: null,
      name: 'Pikachu',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 145000,
      contribution: 0,
      total: 145000,
    },
    {
      userId: 10,
      tournamentId: null,
      name: 'Nhà Cái',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 125000,
      contribution: 0,
      total: 125000,
    },
    {
      userId: 11,
      tournamentId: null,
      name: 'Khoa Nguyen',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 125000,
      contribution: 0,
      total: 125000,
    },
    {
      userId: 12,
      tournamentId: null,
      name: 'Erik',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 155000,
      contribution: 0,
      total: 155000,
    },
    {
      userId: 13,
      tournamentId: null,
      name: 'Terry Mai',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 95000,
      contribution: 0,
      total: 95000,
    },
    {
      userId: 14,
      tournamentId: null,
      name: 'PT',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 145000,
      contribution: 0,
      total: 145000,
    },
    {
      userId: 15,
      tournamentId: null,
      name: 'PT',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 145000,
      contribution: 0,
      total: 145000,
    },
    {
      userId: 16,
      tournamentId: null,
      name: 'PT',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 115000,
      contribution: 0,
      total: 115000,
    },
    {
      userId: 17,
      tournamentId: null,
      name: 'Joseph',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 95000,
      contribution: 0,
      total: 95000,
    },
    {
      userId: 18,
      tournamentId: null,
      name: 'Tamo',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 175000,
      contribution: 0,
      total: 175000,
    },
    {
      userId: 19,
      tournamentId: null,
      name: 'bna',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 145000,
      contribution: 0,
      total: 145000,
    },
    {
      userId: 20,
      tournamentId: null,
      name: 'Stephen',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 145000,
      contribution: 0,
      total: 145000,
    },
    {
      userId: 21,
      tournamentId: null,
      name: 'Thích Car Money',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 180000,
      contribution: 0,
      total: 180000,
    },
    {
      userId: 22,
      tournamentId: null,
      name: 'Chó là bạn',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 105000,
      contribution: 0,
      total: 105000,
    },
    {
      userId: 23,
      tournamentId: null,
      name: 'Dragon Killer',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 145000,
      contribution: 0,
      total: 145000,
    },
    {
      userId: 24,
      tournamentId: null,
      name: 'FA Champion',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 165000,
      contribution: 0,
      total: 165000,
    },
    {
      userId: 25,
      tournamentId: null,
      name: 'Mai Nguyen',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 115000,
      contribution: 0,
      total: 115000,
    },
    {
      userId: 26,
      tournamentId: null,
      name: 'kenny',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 125000,
      contribution: 0,
      total: 125000,
    },
    {
      userId: 27,
      tournamentId: null,
      name: 'Jo Jo De Mango',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 135000,
      contribution: 0,
      total: 135000,
    },
    {
      userId: 28,
      tournamentId: null,
      name: 'ShiNami',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 155000,
      contribution: 0,
      total: 155000,
    },
    {
      userId: 29,
      tournamentId: null,
      name: 'Mike Le',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 155000,
      contribution: 0,
      total: 155000,
    },
    {
      userId: 30,
      tournamentId: null,
      name: 'Marie',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 145000,
      contribution: 0,
      total: 145000,
    },
    {
      userId: 31,
      tournamentId: null,
      name: 'PT',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 95000,
      contribution: 0,
      total: 95000,
    },
    {
      userId: 32,
      tournamentId: null,
      name: 'Bé Dâu',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 135000,
      contribution: 0,
      total: 135000,
    },
    {
      userId: 33,
      tournamentId: null,
      name: 'Tu Truong\t',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 115000,
      contribution: 0,
      total: 115000,
    },
    {
      userId: 34,
      tournamentId: null,
      name: 'Hong Trinh\t',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 155000,
      contribution: 0,
      total: 155000,
    },
    {
      userId: 35,
      tournamentId: null,
      name: 'XoiLacTV',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 155000,
      contribution: 0,
      total: 155000,
    },
    {
      userId: 36,
      tournamentId: null,
      name: 'Terry Nay',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 145000,
      contribution: 0,
      total: 145000,
    },
    {
      userId: 37,
      tournamentId: null,
      name: 'Ben Tang\t',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 175000,
      contribution: 0,
      total: 175000,
    },
    {
      userId: 38,
      tournamentId: null,
      name: 'Luke Nguyen\t',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 205000,
      contribution: 0,
      total: 205000,
    },
    {
      userId: 39,
      tournamentId: null,
      name: 'Telvin Nguyen\t',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 125000,
      contribution: 0,
      total: 125000,
    },
    {
      userId: 40,
      tournamentId: null,
      name: 'Contributor',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 105000,
      contribution: 0,
      total: 105000,
    },
    {
      userId: 41,
      tournamentId: null,
      name: 'Win Tran',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 155000,
      contribution: 0,
      total: 155000,
    },
    {
      userId: 42,
      tournamentId: null,
      name: 'công chúa',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 135000,
      contribution: 0,
      total: 135000,
    },
    {
      userId: 43,
      tournamentId: null,
      name: 'Trong Tran\t',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 165000,
      contribution: 0,
      total: 165000,
    },
    {
      userId: 44,
      tournamentId: null,
      name: 'tuntunli',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 125000,
      contribution: 0,
      total: 125000,
    },
    {
      userId: 45,
      tournamentId: null,
      name: 'Mouse',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 155000,
      contribution: 0,
      total: 155000,
    },
    {
      userId: 46,
      tournamentId: null,
      name: 'Fi-bi',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 155000,
      contribution: 0,
      total: 155000,
    },
    {
      userId: 47,
      tournamentId: null,
      name: 'Anh Hạt Dẻ',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 115000,
      contribution: 0,
      total: 115000,
    },
    {
      userId: 48,
      tournamentId: null,
      name: 'Ông Quại đây',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 125000,
      contribution: 0,
      total: 125000,
    },
    {
      userId: 49,
      tournamentId: null,
      name: 'Tội đồ của nước mắt',
      remainingDebtOtherFee: 0,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 115000,
      contribution: 0,
      total: 115000,
    },
    {
      userId: 50,
      tournamentId: null,
      name: 'San',
      remainingDebtOtherFee: 90000,
      otherFeeContribution: 0,
      remainingBonus: 0,
      paidBonus: 0,
      remainingDebt: 60000,
      contribution: 0,
      total: 150000,
    },
  ],
  totalRemainingDebt: 6555000,
  totalContribution: 0,
};
