version: '3.3'

services:
  funbetReact:
    image: nginx:1.12
    ports:
      - '83:80'
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./dist/:/usr/share/nginx/html/
    hostname: nginx-react-spa
    restart: always
