# create and drop tables and sequences, loads import.sql
spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost/funbet}
    username: ${USER_NAME:dbapplication_user}
    password: ${PASSWORD:dbapplication_user}
    driver-class-name: org.postgresql.Driver
    jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect

    hikari:
      connection-timeout: 60000
      maximum-pool-size: 15

spring.flyway:
  locations: classpath:/migration
  url: ${JDBC_URL:jdbc:postgresql://localhost/funbet}
  username: ${USER_NAME:dbapplication_user}
  password: ${PASSWORD:dbapplication_user}
